- Makefile
Some distros needs more flexibility. For example Exherbo uses `/usr/x86_64-pc-linux-gnu` as a `PREFIX` on x86 64bit platforms while man-pages still resides in `/usr/share/man`. Also some tools have target-specific prefix like `x86_64-pc-linux-gnu-pkg-config`.
- allow overriding BINDIR and MANDIR
- allow overriding pkg-config
> Make install more configurable

- platform/freebsd/freebsd.h
Verified that it's working on 10.0-RELEASE-p12.
Is that cool if I put this into freebsd port tree?
> Make freebsd's do_socketcall signature the same as in linux.

- attach.c
The warning seems to be spurious. fixes #63
> suppress a gcc unitialized-var warning

- platform/freebsd/freebsd_ptrace.c
Passing NULL to the data parameter in calls to ptrace(2) causes failures
on 64-bit FreeBSD 9 installations, where GCC 4.2.1 complains like this:
```
platform/freebsd/arch/x86_common.h: In function 'arch_get_register':
platform/freebsd/arch/x86_common.h:48: warning: cast from pointer to integer of different size
platform/freebsd/arch/x86_common.h: In function 'arch_set_register':
platform/freebsd/arch/x86_common.h:57: warning: cast from pointer to integer of different size
platform/freebsd/arch/x86_common.h:59: warning: cast from pointer to integer of different size
platform/freebsd/freebsd_ptrace.c: In function 'ptrace_memcpy_to_child':
platform/freebsd/freebsd_ptrace.c:267: warning: cast from pointer to integer of different size
platform/freebsd/freebsd_ptrace.c: In function …
```
> FreeBSD: Do not try to cast NULL to int.

- reptyr.c
This change should take care of the FIXME comment about the `SIGWINCH` race (probably a very silly race, but I guess fewer FIXMEs are good) by using `pselect`: I totally used https://lwn.net/Articles/176911/ as a reference to crib from.
> Use pselect to avoid a WINCH race

- platform/linux/linux_ptrace.c
The compilation on musl fails because __ptrace_request enum does not exist. All the PTRACE_* constants from ptrace.h are simple defined integers. int is used instead of enum when PTRACE_TRACEME is defined in preprocessing.
> fix compilation on musl (or libc without __ptrace_request enum)

- platform/platform.h
When `void` is missing it means the arguments to the function are not
specified, not that there are no arguments.
> Fix prototype for get_pt

- .travis.yml
- attach.c
- test/basic.py
- test/tty-steal.py
- test/victim.c
After adding a whole bunch of debugging, conclude that `ptrace` just seems to be ~completely blocked inside Travis' containers, so go back to VMs.
> Fix Travis tests

- platform/linux/arch/powerpc.h
- platform/linux/linux_ptrace.c
Implemented and tested on Gentoo ppc 32-bit (kernel 4.17.6, gcc 7.3.0). ppc64 not yet tested. Reference issue #89
> Implement PowerPC architecture support.

- attach.c
This ensures it actually dies. Fixes #95
> Wait for the dummy child after killing it.

- Makefile
- attach.c
- platform/freebsd/arch/default-syscalls.h
- platform/freebsd/arch/x86_common.h
- platform/linux/arch/aarch64.h
- platform/linux/arch/amd64.h
- platform/linux/arch/default-syscalls.h
- platform/linux/arch/i386.h
- platform/linux/arch/powerpc.h
- platform/linux/arch/x86_common.h
- platform/linux/linux.c
- platform/linux/linux_ptrace.c
- ptrace.h
This PR adds support for Linux on aarch64, which requires a number of changes besides the arch specific header.
Being a more recently architecture, Linux on aarch64 does not implement older syscalls such as `open`, `fork` and `dup2`. I added compatibility wrappers that emulate `fork` using `clone` and `dup2` using `dup3`. I replaced `open` with `openat`, which I believe is available on all supported systems.
aarch64 also does not support certain ptrace requests, such as `PTRACE_GETREGS`, `PTRACE_SETREGS`, `PTRACE_PEEKUSER` and `PTRACE_POKEUSER`. Instead, `PTRACE_GETREGSET` and `PTRACE_SETREGSET` must be used for all register manipulations. I believe these are available on all supported systems, so we shouldn't need special cases for aarch64.
I also switched from using the `user` struct to …
> Add support for Linux on aarch64

- test/basic.py
- test/tty-steal.py
- test/util.py
pexpect.EOF apparently waits for the child to die
We actually just want to check for EOF on that FD.
I'm not entirely sure how this ever worked, now.
> Fix the TravisCI build

- attach.c
This commit added a ptrace_wait to reap the dummy before
ptrace_detach_child.  On FreeBSD, this leaves us stuck waiting on a child
that cannot be reaped because ptrace is still attached.
Signed-off-by: Kyle Evans <kevans@FreeBSD.org>
> Fix usage on FreeBSD after c6f10c6db3f0

- platform/freebsd/freebsd.c
This is a possibility, and reptyr does not care about these. This is mostly
a cosmetic issue, as reptyr then complains because it can't use dup2() on
fd=-1.
Signed-off-by: Kyle Evans <kevans@FreeBSD.org>
> freebsd: ignore fd < 0 in the vnodes returned

- platform/freebsd/freebsd.c
- platform/freebsd/freebsd_ptrace.c
Around ~4 commits needed to make it happen; in an ideal world, the difference in remote syscall execution doesn't matter, so even on releases that don't have the proper op for grabbing return value information `reptyr -T` *can* still work.
> freebsd: fill in missing details for reptyr -T to work

- Makefile
- test/basic.py
- test/tty-steal.py
- test/victim.c
My local master branch contains cirrus configs that tested both python2 and python3 compatibility on Linux -- neither work on FreeBSD still due to issues with the victim running under pexpect that I'm working over, but all tests passed on both versions with these relatively minor changes.
prctl-type manipulation isn't needed on FreeBSD, as we don't have any facility that will restrict PT_ATTACH beyond a bunch of bits that we wouldn't be able to affect anyways as the debugger.
> test: modify a bit for other-platform/python compatibility

- .cirrus.yml
Signed-off-by: Kyle Evans <kevans@FreeBSD.org>
--
You can visit https://cirrus-ci.com to sign up for the integration with GitHub to view the results easily. I'm still working out test details locally here on FreeBSD, but I can at least confirm that the tests are OK under Cirrus' Linux setup, at least.
> Add Cirrus CI support, Linux build+test and FreeBSD build

- .cirrus.yml
- platform/freebsd/freebsd.c
- test/basic.py
As described in the commit messages, we actively haven't implemented TIOCNOTTY in at least 17 years. I have an implementation WIP, but it will be a while before this becomes usable from a CI standpoint. =-(
The tty-stealing test uncovered a bug in my implementation where I didn't actually make sure the master fds we were gathering corresponded to the victim (d'oh!). Easily fixed- do that, and now the tests pass and the implementation is more correct than my initial testing!
Thanks again for this fine piece of software. =)
> FreeBSD: Fix tty stealing, enable at least that test

- ptrace.h
This fixes compilation error, which was found while using musl for powerpc:
```
In file included from attach.c:43:0:
ptrace.h:69:20: error: field 'regs' has incomplete type
struct pt_regs regs;
^~~~
<builtin>: recipe for target 'attach.o' failed
```
> Update ptrace.h: include <asm/ptrace.h> for Linux

- platform/freebsd/freebsd.c
This API will not touch *count in the error case, so we're
left with stack garbage.
Signed-off-by: Kyle Evans <kevans91@ksu.edu>
> freebsd: initialize count to 0 before procstat_getprocs()

- platform/freebsd/freebsd.c
Technically this is a warning, but warnings treated as errors.
> fix(freebsd): Initialize state in check_proc_stopped.

- .cirrus.yml
Notably:
- CIRRUS_CLONE_DEPTH is not necessary, the default is 50 and this is cargo-cult from the template I was using
- Switch to FreeBSD 12.2, 12.1 will go EoL at the end of this month
- Switch to Python 3.7, we've already removed the Python 2.7 flavor of py-pexpect in our Python 2.7 deprecation effort
> Fix up the Cirrus bits

- platform/linux/linux_ptrace.c
The code was previously using (status >> 8) & PTRACE_EVENT_FORK to check for
a fork event, but the event is in (status >> 16), and PTRACE_EVENT_* is an
enumeration, not a bit mask. What was actually being tested was the low bit of
the signal, which was always set (since SIGTRAP is 5).
Presumably the old code was working fine because the child PID is only used
immediately after a fork call, but this event handling is more correct.
> Fix Linux ptrace event handling

- platform/linux/arch/riscv64.h
- platform/linux/linux_ptrace.c
- ptrace.h
This PR adds support for Linux on riscv64.
I have tested these changes under Linux on a physical RISC-V board.
> Add support for Linux on riscv64

- platform/freebsd/arch/x86_common.h
Fix the following error under LLVM 13 on FreeBSD.
In file included from platform/freebsd/freebsd_ptrace.c:69:
In file included from platform/freebsd/arch/amd64.h:23:
platform/freebsd/arch/x86_common.h:45:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
int ret;
^
platform/freebsd/arch/x86_common.h:54:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
int ret;
^
2 errors generated.
> x86_common.h: Fix buld under LLVM 13 on FreeBSD

- .cirrus.yml
(Stab in the dark based on [this](https://www.freebsd.org/cgi/ports.cgi?query=pexpect&stype=all), but let's see if it works)
> Update FreeBSD build for python3.8 transition

- test/basic.py
ECHO: world
final
Traceback (most recent call last):
File "test/basic.py", line 27, in <module>
expect_eof(child.child_fd)
File "/build/source/test/util.py", line 13, in expect_eof
raise AssertionError("Expected EOF, got read: `{}'".format(data))
AssertionError: Expected EOF, got read: `
'
When I run in python3 I get `b"\r\n"`
Also a test I did to confirm:
```
42sh$ printf "a\r\nb\nc" | ./victim | xxd
00000000: 4543 484f 3a20 610d 0a45 4348 4f3a 2062  ECHO: a..ECHO: b
00000010: 0a45 4348 4f3a 2063                      .ECHO: c
```
> fix: expect EOL in test

- debian/changelog
- debian/control
- debian/copyright
- debian/upstream/metadata
Fix some issues reported by lintian
* Use secure copyright file specification URI. ([insecure-copyright-format-uri](https://lintian.debian.org/tags/insecure-copyright-format-uri))
* Set upstream metadata fields: Bug-Database, Bug-Submit, Repository, Repository-Browse. ([upstream-metadata-file-is-missing](https://lintian.debian.org/tags/upstream-metadata-file-is-missing), [upstream-metadata-missing-bug-tracking](https://lintian.debian.org/tags/upstream-metadata-missing-bug-tracking), [upstream-metadata-missing-repository](https://lintian.debian.org/tags/upstream-metadata-missing-repository))
* Update standards version to 4.6.1, no changes needed. ([out-of-date-standards-version](https://lintian.debian.org/tags/out-of-date-standards-version))
These changes affect the binary packages:
[The …
> Fix some issues reported by lintian

- .cirrus.yml
- platform/freebsd/arch/aarch64.h
- platform/freebsd/arch/x86_common.h
- platform/freebsd/freebsd_ptrace.c
This also has some minor cleanup of Cirrus config in it to bump versions and run the basic test now that we support TIOCNOTTY on all supported versions.
> freebsd: add aarch64 support

- platform/freebsd/arch/aarch64.h
- platform/freebsd/arch/arm.h
- platform/freebsd/arch/x86_common.h
- platform/freebsd/freebsd_ptrace.c
This kills off some dead code (we don't need `saved_syscall` and `arch_set_syscall` can never fail), adds support for spilling syscall args to the stack, and adds 32-bit arm support which required args-on-stack.
> freebsd: a little more cleanup and arm32 support

- Makefile
The current version of the build system uses `pkgconfig` to discover the location of the bash completion scripts. Typically, this script outputs a directory under the `/usr` prefix. Unfortunately, if the user chooses to override the build prefix with PREFIX, the BASHCOMPLETION variable is not also updated.
In this commit, I propose to correct this issue by simply looking for the `/usr` prefix and substituting it with the contents of `PREFIX`. I've tested this approach using my `stow`-based "package" collection, where I build commands with custom prefixes, and do not grant root or sudo privileges when doing so. It appears to function normally for me.
> fix(Makefile): Make bash completion honor PREFIX
